# Generated by Django 4.1.5 on 2023-01-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whisky',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='abv',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='age',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='bottled_year',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='long_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='sale_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='sale_price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='scraped_at',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='size',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='updated_at',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='vintage',
            field=models.CharField(max_length=255),
        ),
    ]
