# Generated by Django 4.1.5 on 2023-01-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_api', '0002_whisky_title_alter_whisky_abv_alter_whisky_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whisky',
            name='whiskybase_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
