# Generated by Django 4.1.5 on 2023-01-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_api', '0003_whisky_whiskybase_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whisky',
            name='short_description',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
