# Generated by Django 4.1.5 on 2023-01-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_api', '0004_alter_whisky_short_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='whisky',
            index=models.Index(fields=['short_description'], name='filter_api__short_d_b32916_idx'),
        ),
    ]
