# Generated by Django 4.1.5 on 2023-01-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_api', '0005_whisky_filter_api__short_d_b32916_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='whisky',
            name='filter_api__short_d_b32916_idx',
        ),
        migrations.AddIndex(
            model_name='whisky',
            index=models.Index(fields=['title', 'auction_house_names', 'short_description', 'long_description', 'sale_price', 'sale_date', 'url', 'distillery', 'age', 'cask', 'vintage', 'bottled_year', 'abv', 'size', 'bottler', 'source', 'updated_at', 'scraped_at', 'image', 'whiskybase_url'], name='filter_api__title_379502_idx'),
        ),
    ]
