# Generated by Django 4.1.5 on 2023-01-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_api', '0006_remove_whisky_filter_api__short_d_b32916_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='whisky',
            name='filter_api__title_379502_idx',
        ),
        migrations.AlterField(
            model_name='whisky',
            name='short_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='whisky',
            index=models.Index(fields=['short_description'], name='short_description_idx'),
        ),
    ]
